### ISSUE TITLE
Remove payed enough constraint

### ISSUE THREAD

**Issue by edruid** [edruid/Nitroxy-retail-system#13]
Remove the constraint that you have to write the payed amount to finish a sale.

**Comment by p-blomberg** [comment]
Why?

**Comment by edruid** [comment]
I was asked to remove it to speed up usage. I'm considering closing it as wont fix but I'll let it lie dormant for a while to see if others feel the same.

**Comment by edruid** [comment]
Closing as wont fix as no one has asked for it in about 6 months.
