### ISSUE TITLE
Dagsavslut: NitroXy har andra behov än Proxxi

### ISSUE THREAD

**Issue by p-blomberg** [edruid/Nitroxy-retail-system#40]
Ordningen att först räkna kassan och sedan bokföra dagsavslutet är helt fel för NitroXy. Vi kan aldrig sluta sälja under så lång tid som krävs för att räkna kassan. 
Eftersom vi inte använder bokföringsdelen av systemet är det inte heller intressant att räkna ut kassadifferensen. Att bara kunna registrera tidpunkt för dagsavslutet och vilka transaktioner (kvitto nr x till y) som ingår, och då få fram en summa på försäljningen för dessa transaktioner, skulle räcka.

**Comment by edruid** [comment]
Eftersom ni inte använder bokföringsdelen av systemet så är lösningen att göra dagsavslut och fylla i 0 kr i fältet. Sedan tittar du på transaktionens Försäljning och Lager delar.

Om detta inte räcker får du gärna förklara mer vad du vill ha och öppna issuen igen.
